Integrate components responsive
DesApp-2023c3-Grupo-3/BulletinBoardClient pull request #127
Opened 2024-09-07 00:27 UTC by lucianogaregnani

**Que se hizo?**
Se integro las nuevas cards en el mobile, junto con la integración de la nueva paginación
**Cómo se hizo?**
Para las cards, se usó el componente Card de NextUI, y para la paginación se cambió el endpoint y se uso el componente de paginación de NextUI también
**Cómo se puede probar?**
Para ver la paginación, simplemente ir a las diferentes secciones de Admin, para ver las cards, apretar F12 y activar el modo celular, luego ir a las secciones de Admin.

2024-09-07 00:38 UTC, tomas0011 requested changes

2024-09-07 00:38 UTC, tomas0011 commented on src/components/AdminWeb/components/Table/TableRow.tsx
> +              {columns.get(columnName)?.call(item, item) || 'aaa'}
aaa??

2024-09-07 00:38 UTC, tomas0011 commented on src/components/AdminWeb/utils/createSchedule.ts
> +      .map((d) => d.charAt(0).toUpperCase() + d.slice(1).toLowerCase())
Que es a, b d?

2024-09-07 00:38 UTC, tomas0011 commented on src/components/AdminWeb/components/Mobile/ListOfAdvertisingCards.tsx
> +        return (
No hace falta return aca

2024-09-07 00:38 UTC, tomas0011 commented on src/components/AdminWeb/components/Mobile/ListOfAdvertisingCards.tsx
> +  dataJson: any[];
Any any any any :v

2024-09-12 21:42 UTC, ValentinoChiappanni commented
@lucianogaregnani En el celu no se ve la lupita para buscar avisos

2024-09-12 21:43 UTC, ValentinoChiappanni requested changes
Revisar que no sale la lupita para buscar avisos en celu
@lucianogaregnani

2024-09-18 00:57 UTC, ValentinoChiappanni commented
@lucianogaregnani No pasa del loggin

2024-09-18 16:47 UTC, merged